server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shaolin182-transactions/transactions-config.git
          ignore-local-ssh-settings: true
          passphrase: ${CONFIG_PASSPHRASE}
          privateKey: ${CONFIG_PRIVATEKEY}

logging:
  level:
    root: DEBUG