apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-database
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: esdata
    namespace: transactions
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  local:
    path: /mnt/k8s/data/esdata
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - local