apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-database
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: transactions-data-volume
    namespace: transactions
  capacity:
    storage: 200Mi
  local:
    path: /mnt/k8s/data/transactions
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - local