version: "3.7"
services:

  transactions-server:
    container_name: transactions-server
    image: jugirard/transactions-java-server:latest
    ports:
      - "8080:8080"
    environment:
      - TARGET_ENV
    depends_on:
      - mongo

  transactions-sync-data:
    container_name: transactions-sync-data
    image: jugirard/transactions-sync-process:latest
    ports:
      - "8081:8080"
    environment:
      - TARGET_ENV
    restart: on-failure
    depends_on:
      - elasticsearch
      - mongo

  mongo:
    container_name: transactions-mongo-db
    image: mongo:4.2.6
    volumes:
      - transactions-data-volume:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    container_name: transactions-elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    build: ./kibana/
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  transactions-data-volume:
  esdata:
    driver: local