version: "3.7"
services:

  transactions-config-server:
    container_name: transactions-config-server
    image: jugirard/transactions-config-server:v1.2.4.2
    ports:
      - "8888:8888"
    environment:
      - CONFIG_PASSPHRASE
      - CONFIG_PRIVATEKEY

  mongo:
    container_name: transactions-mongo-db
    image: mongo:6.0.7
    ports:
      - "27017:27017"

  elasticsearch:
    container_name: transactions-elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    build: ./kibana/
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE
      - DB_USER
      - DB_SCHEMA=public
      - DB_PASSWORD
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
    ports:
      - 8082:8080
    depends_on:
      - postgres

volumes:
  transactions-data-volume:
  esdata:
    driver: local
  postgres_data_keycloak:
    driver: local