- name: Install Keycloak
  hosts: k8s
  tasks:
    - ansible.builtin.include_role:
        name: deploy_keycloak

- name: Install Elastic Search & Kibana
  hosts: k8s
  tasks:
    - ansible.builtin.include_role:
        name: deploy_elk

- name: Configure Keycloak
  hosts: k8s
  tasks:
    - ansible.builtin.include_role:
        name: configure_keycloak

- name: Transactions Deployment
  hosts: k8s
  tasks:
    - ansible.builtin.include_role:
        name: deploy_transactions