# Import Kibana data
- name: Configure Kibana Dashboard
  ansible.builtin.uri:
    url: "http://{{ transactions_kibana_fqdn }}/api/kibana/dashboards/import"
    method: POST
    body: "{{ lookup('ansible.builtin.file','kibana-dashboard.json') }}"
    body_format: json
    headers:
      kbn-xsrf: "reporting"
  when: kibana.deploy  == "true"