- name: Add Helm Repo
  kubernetes.core.helm_repository:
    repo_name: "{{ es.helm_repo.name }}"
    repo_url: "{{ es.helm_repo.url }}"

- name: Deploy Elasticsearch
  kubernetes.core.helm:
    release_name: "{{ es.release_name }}"
    release_namespace: "{{ es.namespace }}"
    chart_ref: "{{ es.helm_repo.chart }}"
    chart_version: "{{ es.helm_repo.version }}"
    host: "{{ k8s_api }}"
    state: present

- name: Wait till pods are running
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    namespace: "{{ es.namespace }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Deploy Kibana
  kubernetes.core.helm:
    release_name: "{{ kibana.release_name }}"
    release_namespace: "{{ kibana.namespace }}"
    chart_ref: "{{ kibana.helm_repo.chart }}"
    chart_version: "{{ kibana.helm_repo.version }}"
    host: "{{ k8s_api }}"
    state: present
    values: "{{ kibana.chart_values }}"
- name: Wait till pods are running
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    namespace: "{{ kibana.namespace }}"
    wait_sleep: 10
    wait_timeout: 360




