k8s:
  vars:
    kibana:
      helm_repo:
        name: bitnami
        url: https://charts.bitnami.com/bitnami
        chart: bitnami/kibana
        version: 10.4.6

      release_name: transactions-kibana

      namespace: kibana

      hostname: kibana.127-0-0-1.nip.io

#      values: |
#        # Content of kibana values.yaml
#        elasticsearch:
#          port: 9200
#          hosts:
#            - transactions-es-elasticsearch.elasticsearch.svc.cluster.local
#
#        ingress:
#          enabled: true
#          ingressClassName: nginx
#          hostname: kibana.127-0-0-1.nip.io
#          pathType: Prefix