elasticsearch:
  port: 9200
  hosts:
    - transactions-es-elasticsearch.elasticsearch.svc.cluster.local

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: kibana.127-0-0-1.nip.io
  pathType: Prefix