global:
  storageClass: local-storage

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.127-0-0-1.nip.io
  pathType: Prefix

postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: local-storage
      existingClaim: postgres-data-keycloak