- name: Undeploy Transactions App
  kubernetes.core.helm:
    release_name: "{{ transactions.helm_release_name }}"
    release_namespace: "{{ transactions.helm_release_name }}"
    chart_ref: "{{ transactions.chart_ref }}"
    chart_version: "{{ transactions.chart_version }}"
    host: "{{ k8s_api }}"
    state: absent
    kubeconfig: /etc/config/.kube/config