apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transactions-data-volume
  namespace: transactions
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 200Mi
