- name: Add Helm Repo
  kubernetes.core.helm_repository:
    repo_name: "{{ transactions.helm_repo.name }}"
    repo_url: "{{ transactions.helm_repo.url }}"

- name: Deploy Transactions App
  kubernetes.core.helm:
    release_name: "{{ transactions.helm_release_name }}"
    release_namespace: "{{ transactions.helm_release_name }}"
    chart_ref: "{{ transactions.chart_ref }}"
    chart_version: "{{ transactions.chart_version }}"
    create_namespace: true
    host: "{{ k8s_api }}"
    state: present
    values: "{{ transactions.chart_values }}"
    kubeconfig: /etc/config/.kube/config



