apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-keycloak
  namespace: keycloak
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
