# This is a basic workflow to help you get started with Actions

name: Integration Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  schedule:
    - cron: '00 23 * * 5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Run app
    - name: Build the stack
      run: docker-compose up -d

    - name: Show logs
      run: docker-compose logs

    # Run integration tests with newman
    - name: Run postman tests
      uses: matt-ball/newman-action@master
      with:
        collection: postman/Transactions.postman_collection.json
        environment: postman/Transactions-localhost.postman_environment.json

    # Stop this app
    - name: Stop the stack
      run: docker-compose down -v
